services:
  web:
    build: .
    image: dayplanner:latest
    container_name: dayplanner
    ports:
      - "${PORT:-8383}:8383"
    volumes:
      - dayplanner_data:/app/data
    environment:
      - DATA_DIR=/app/data
      - LATITUDE=52.2777
      - LONGITUDE=6.1730
      - LOG_LEVEL=INFO
      - TZ=${TZ:-Europe/Amsterdam}
    restart: unless-stopped
volumes:
  dayplanner_data:
